### ISSUE TITLE
Error in composer install

### ISSUE THREAD

**Issue by maalvarez82** [MartMbithi/LMS#20]
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.

Plaease help me install, I use teamviewer.

**Comment by MartMbithi** [comment]
you are trying to run the system?

**Comment by maalvarez82** [comment]
yes!

**Comment by maalvarez82** [comment]
This error!

**Comment by MartMbithi** [comment]
Okay lemme look into it and fix it asap
