### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by nnamdei** [MartMbithi/LMS#21]
I cloned, used the composer install and migrate commands and it worked fine. 

PHP verison is 7.3.8

- I used the login details in the readme file in the repository but showed a blank page when i login. 
- i signed up for a new student account but got the same blank page.

I checked the devtools and found out this error 

> pages_std_signup.php:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

> Stack trace:
> #0 {main}
>   thrown in /Applications/MAMP/htdocs/lms-test/public/LMS_Core/admin/pages_admin_index.php on line 10

**Comment by MartMbithi** [comment]
Hello @nnamdei  let me update my readme.md and fix those errors.

**Comment by nnamdei** [comment]
followed the new instructions and got the same error of failed to load resource. So i downgraded my php version to 7.1.31 and it is showing no error in the dev tool console and a blank page. 

could it be an issue with the php version, since the the composer.json file has 7.1.26 version?

**Comment by MartMbithi** [comment]
upgrade to  PHP 7.3.15-3, and also i have fixed those run time errors.

**Comment by nnamdei** [comment]
@MartMbithi i have followed these instructions and got this error.
![Screenshot 2020-04-25 at 11 02 20 AM](https://user-images.githubusercontent.com/26845388/80277078-76156300-86e4-11ea-9d5e-30289b2ca333.png)
